import { Component, OnInit, computed, inject, signal } from '@angular/core';

import { AdminService } from '../../core/admin.service';
import { CatalogItem } from '../../core/models';

@Component({
  selector: 'app-catalog',
  templateUrl: './catalog.html',
  styleUrl: './catalog.scss',
})
export class Catalog implements OnInit {
  private readonly admin = inject(AdminService);
  protected readonly limit = 20;

  protected readonly loading = signal(false);
  protected readonly error = signal<string | null>(null);
  protected readonly items = signal<CatalogItem[]>([]);
  protected readonly total = signal(0);
  protected readonly offset = signal(0);

  protected readonly page = computed(() => Math.floor(this.offset() / this.limit) + 1);
  protected readonly pageCount = computed(() => Math.max(1, Math.ceil(this.total() / this.limit)));

  /** Collapsible help notes shown above the table. -1 = all closed. */
  protected readonly openNote = signal<number>(-1);
  protected readonly notes = [
    {
      q: 'What is anime?',
      a: `Anime is the style of animation that comes from Japan — essentially Japanese ` +
         `cartoons (the word is how Japanese pronounces "animation"). Unlike the Western ` +
         `assumption that cartoons are just for kids, anime spans every genre — action, ` +
         `romance, horror, sci-fi, comedy, slice-of-life, sports, deep psychological drama — ` +
         `for children, teens, and adults. It appears as TV series, films, and shorts, and is ` +
         `often based on manga (Japanese comics) or light novels.`,
    },
    {
      q: 'About this catalog',
      a: `Each row is one anime from an ORIGINAL, fully synthetic dataset generated by the ` +
         `platform — no third-party data, so it's free of copyright concerns and can scale to ` +
         `100k–1M titles. Columns: id, Title, Year, Score (out of 10), Studio, Genres. The ` +
         `catalog is generated in concept (genre) batches; a sample is embedded into the vector ` +
         `store that powers recommendations. Run or refresh from the Ingestion tab.`,
    },
    {
      q: 'How recommendations work',
      a: `When a user describes what they want to watch, the recommender service embeds the ` +
         `query, runs a semantic search over these titles' synopses in the vector store, then ` +
         `asks a Groq-hosted LLM to pick three matches and explain each one.`,
    },
  ];

  protected toggleNote(i: number): void {
    this.openNote.set(this.openNote() === i ? -1 : i);
  }

  ngOnInit(): void {
    this.load();
  }

  protected load(): void {
    this.loading.set(true);
    this.error.set(null);
    this.admin.getCatalog(this.limit, this.offset()).subscribe({
      next: (p) => {
        this.items.set(p.items);
        this.total.set(p.total);
        this.loading.set(false);
      },
      error: (err) => {
        this.error.set(err?.error?.detail ?? 'Could not load catalog. Has ingestion run yet?');
        this.loading.set(false);
      },
    });
  }

  protected prev(): void {
    if (this.offset() === 0) return;
    this.offset.set(Math.max(0, this.offset() - this.limit));
    this.load();
  }

  protected next(): void {
    if (this.page() >= this.pageCount()) return;
    this.offset.set(this.offset() + this.limit);
    this.load();
  }
}
